remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "default"
plugins:
- jekyll-remote-theme
title: DIIS Dev Sec Ops1
author: Suttipong
description: Diis Desc
header_pages:
  - about.md
  - Publications.md
  - teaching.md
  - game.md
  - index.md
